name: pawlly
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.3+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter  

  #firebase
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  firebase_crashlytics: ^3.3.3
  firebase_analytics: ^10.4.4

  nb_utils: ^6.0.3
  google_fonts: ^5.1.0
  html: ^0.15.4
  http: ^1.1.0
  intl: ^0.18.0
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.11
  share_plus: 7.0.2

  # SOCIAL LOGIN
  the_apple_sign_in: ^1.1.1
  google_sign_in: ^6.1.4
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.9
  permission_handler: ^11.0.1

  # State Management
  get: ^4.6.5

  # Notification
  onesignal_flutter: ^5.0.2

  # Payment
  flutter_stripe: ^9.3.0
  razorpay_flutter: ^1.3.5
  flutterwave_standard: ^1.0.8
  cinetpay: ^1.0.7
  flutter_paypal_checkout:
    git:
      url: https://github.com/Raj-GMITS/flutter_paypal_checkout.git
      ref: main

  flutter_paystack:
    git:
      url: https://github.com/Raj-GMITS/flutter_paystack.git
      ref: master

  #Storage
  get_storage: ^2.1.1

  #PhotoViewGallery

  photo_view: ^0.14.0

  #intent
  android_intent_plus: ^4.0.1

  datepicker_dropdown: ^0.0.7+5
  file_picker: ^5.3.2
  image_picker: ^1.0.0
  country_picker: ^2.0.20

  # MAP
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  flutter_localizations:
    sdk: flutter
  lottie: ^2.5.0
  flutter_html: ^3.0.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/flags/
    - assets/images/
    - assets/icons/
    - assets/images/walkthrough_images/
    - assets/images/dog_paw/
    - assets/images/pet_profile/
    - assets/images/sitter/
    - assets/images/notification/
    - assets/images/shop/
    - assets/images/choosepet/
    - assets/icons/profile_icons/
    - assets/icons/service_icons/
    - assets/icons/navigation/
    - assets/images/brand/
    - assets/lottie/



